### PR TITLE
Adding support for 8u144 release

### PR DESCRIPTION
**Pull request by adipriyantobpn**

### CODE REVIEW

**Comment by freemanjp** [comment]
@adipriyantobpn thanks for the pull request, before accepting your change I need you sign our Contributor License Agreement by clicking on https://cla-assistant.io/gantsign/ansible-role-java?pullRequest=94 and following the instructions.

Thanks

**Comment by adipriyantobpn** [comment]
hi @freemanjp, sure i will..
thanks again for your feedback :)

**Comment by adipriyantobpn** [comment]
thank you so much for merging the PR

**Comment by freemanjp** [comment]
You're welcome, your change can be found in the [4.2.0](https://github.com/gantsign/ansible-role-java/releases/tag/4.2.0) release.

**Pull request merged**
